# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-18 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_auto_20180413_1219'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='turma',
            options={'ordering': ['created_at'], 'verbose_name': 'Turma', 'verbose_name_plural': 'Turmas'},
        ),
        migrations.RemoveField(
            model_name='turma',
            name='oferta',
        ),
        migrations.AddField(
            model_name='turma',
            name='codigo',
            field=models.CharField(default='None', max_length=25, verbose_name='C\xf3digo'),
        ),
    ]
