# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-19 22:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0012_auto_20180412_1800'),
        ('cursos', '0004_auto_20180418_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='alunos',
            field=models.ManyToManyField(to='aluno.Aluno', verbose_name='Aluno'),
        ),
    ]
