# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-20 18:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0012_auto_20180412_1800'),
        ('cursos', '0005_turma_alunos'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(blank=True, choices=[(0, 'Pendente'), (1, 'Aprovado'), (2, 'Cancelado')], default=1, verbose_name='Situa\xe7\xe3o')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='aluno.Aluno', verbose_name='Aluno')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='cursos.Turma', verbose_name='Turma')),
            ],
            options={
                'verbose_name': 'Inscri\xe7\xe3o',
                'verbose_name_plural': 'Inscri\xe7\xf5es',
            },
        ),
        migrations.AlterUniqueTogether(
            name='signup',
            unique_together=set([('aluno', 'turma')]),
        ),
    ]
