# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-20 22:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0006_auto_20180420_1527'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curso',
            options={'ordering': ['created_at'], 'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
    ]
