# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-23 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0007_auto_20180420_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='codigo',
            field=models.CharField(default='None', max_length=25, unique=True, verbose_name='C\xf3digo'),
        ),
    ]
