# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-25 15:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0008_auto_20180423_1724'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='signup',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='signup',
            name='aluno',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='turma',
        ),
        migrations.DeleteModel(
            name='SignUp',
        ),
    ]
