# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-07 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0012_auto_20180412_1800'),
        ('cursos', '0010_auto_20180507_1225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turma',
            name='alunos',
        ),
        migrations.AddField(
            model_name='turma',
            name='alunos_espera',
            field=models.ManyToManyField(related_name='turma_Aluno_espera', to='aluno.Aluno'),
        ),
        migrations.AddField(
            model_name='turma',
            name='alunos_inscritos',
            field=models.ManyToManyField(related_name='turma_Aluno_inscrito', to='aluno.Aluno'),
        ),
    ]
