# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-07 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0012_auto_20180412_1800'),
        ('cursos', '0011_auto_20180507_1234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turma',
            name='alunos_espera',
        ),
        migrations.RemoveField(
            model_name='turma',
            name='alunos_inscritos',
        ),
        migrations.AddField(
            model_name='turma',
            name='alunos',
            field=models.ManyToManyField(to='aluno.Aluno', verbose_name='Aluno'),
        ),
    ]
