# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-09 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0013_auto_20180507_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='dia',
            name='status',
            field=models.CharField(default='', max_length=100, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='turma',
            name='pauta',
            field=models.ManyToManyField(related_name='turma_Pauta', to='cursos.ListaPresenca'),
        ),
    ]
