# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-10 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0014_auto_20180509_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dia',
            name='day',
            field=models.CharField(default='', max_length=100, verbose_name='Day'),
        ),
    ]
