# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-10 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0015_auto_20180510_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dia',
            name='day',
            field=models.DateField(),
        ),
    ]
