# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-22 16:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0012_auto_20180412_1800'),
        ('cursos', '0017_auto_20180510_1445'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorasFaltadas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas_faltadas', models.IntegerField(default=0)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aluno.Aluno')),
            ],
        ),
        migrations.RemoveField(
            model_name='listapresenca',
            name='matriculas',
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='aluno',
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='days',
        ),
        migrations.AlterField(
            model_name='turma',
            name='pauta',
            field=models.ManyToManyField(related_name='turma_Pauta', to='cursos.HorasFaltadas'),
        ),
        migrations.DeleteModel(
            name='Dia',
        ),
        migrations.DeleteModel(
            name='ListaPresenca',
        ),
        migrations.DeleteModel(
            name='Matricula',
        ),
    ]
