# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-28 00:47
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[\\w.@+-]+$'), 'Apenas s\xe3o permitidos letras, n\xfameros ou os caracteres: @ . + - _', 'invalid')], verbose_name='Nome de Usu\xe1rio')),
                ('email', models.EmailField(help_text='Digite seu email criado pelo NCD', max_length=254, unique=True, verbose_name='E-mail')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Nome')),
                ('is_active', models.BooleanField(default=True, verbose_name='Est\xe1 Ativo?')),
                ('is_staff', models.BooleanField(default=False, verbose_name='\xc9 da equipe?')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Data de Entrada')),
            ],
            options={
                'verbose_name': 'Usu\xe1rio',
                'verbose_name_plural': 'Usu\xe1rios',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipe', models.CharField(choices=[('Comunicacao', (('diretor', 'Diretor de Comunica\xe7\xe3o'), ('trainee', 'Trainee de Comunica\xe7\xe3o'))), ('Ensino', (('diretor', 'Diretor de Ensino'), ('instrutor', 'Instrutor de Ensino'))), ('Gestao', (('diretor', 'Diretor Gestor'), ('analista_rh', 'Analista de RH'), ('analista_projetos', 'Analista de Projetos'), ('assessor_adm', 'Assessor Administrativo'))), ('Tecnologia da Informa\xe7\xe3o', (('diretor', 'Diretor de TI'), ('tecnico_dev', 'T\xe9cnico de Desenvolvimento'), ('tecnico_infra', 'T\xe9cnico de Infraestrutura'))), ('Tela Cidad\xe3', (('diretor do tela', 'Diretor do Tela Cidad\xe3'), ('trainee de comunica\xe7\xe3o', 'Trainee de Comunica\xe7\xe3o')))], default=None, max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='PasswordReset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='Chave')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('confirmed', models.BooleanField(default=False, verbose_name='Confirmado')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resets', to=settings.AUTH_USER_MODEL, verbose_name='Usu\xe1rio')),
            ],
            options={
                'ordering': ['-created_at'],
                'verbose_name': 'Nova Senha',
                'verbose_name_plural': 'Novas Senhas',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='equipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Equipe'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
