# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-28 00:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipe',
            name='equipe',
            field=models.CharField(choices=[('Comunicacao', (('diretor', 'Diretor de Comunica\xe7\xe3o'), ('trainee', 'Trainee de Comunica\xe7\xe3o'))), ('Ensino', (('diretor', 'Diretor de Ensino'), ('instrutor', 'Instrutor de Ensino'))), ('Gestao', (('diretor', 'Diretor Gestor'), ('analista_rh', 'Analista de RH'), ('analista_projetos', 'Analista de Projetos'), ('assessor_adm', 'Assessor Administrativo'))), ('TI', (('diretor_ti', 'Diretor de TI'), ('tecnico_dev', 'T\xe9cnico de Desenvolvimento'), ('tecnico_infra', 'T\xe9cnico de Infraestrutura'))), ('Tela', (('diretor do tela', 'Diretor do Tela Cidad\xe3'), ('trainee de comunica\xe7\xe3o', 'Trainee de Comunica\xe7\xe3o')))], default=None, max_length=40),
        ),
        migrations.AlterField(
            model_name='user',
            name='equipe',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.Equipe'),
        ),
    ]
