# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-02 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20180427_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipe',
            name='equipe',
            field=models.CharField(choices=[('COMUNICA\xc7\xc3O', 'Comunica\xe7\xe3o'), ('ENSINO', 'Ensino'), ('GEST\xc3O', 'Gest\xe3o'), ('TECNOLOGIA DA INFORMA\xc7\xc3O', 'Tecnologia da Informa\xe7\xe3o'), ('TELA CIDAD\xc3', 'Tela cidad\xe3')], default='COMUNICA\xc7\xc3O', max_length=30),
        ),
    ]
