# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-02 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_auto_20180502_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipe',
            name='equipe',
            field=models.CharField(choices=[('CO', 'Comunica\xe7\xe3o'), ('EN', 'Ensino'), ('GE', 'Gest\xe3o'), ('TI', 'Tecnologia da Informa\xe7\xe3o'), ('TC', 'Tela Cidad\xe3')], default='CO', max_length=2),
        ),
    ]
