# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-03 18:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_auto_20180502_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='equipe',
        ),
        migrations.DeleteModel(
            name='Equipe',
        ),
    ]
