# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-26 17:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('idade', models.DecimalField(decimal_places=0, max_digits=3)),
                ('telefone', models.CharField(max_length=20)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('email', models.EmailField(default=b'', max_length=100)),
                ('data_entrada', models.DateTimeField(default=django.utils.timezone.now)),
                ('rua', models.CharField(default=b'', max_length=100)),
                ('bairro', models.CharField(default=b'', max_length=100)),
                ('cidade', models.CharField(default=b'', max_length=100)),
                ('numero_matricula', models.CharField(max_length=11, unique=True)),
                ('status', models.CharField(max_length=11)),
                ('nivel_conhecimento', models.CharField(choices=[(b'Excelente', b'Excelente'), (b'Bom', b'Bom'), (b'Regular', b'Regular'), (b'Ruim', b'Ruim')], default=b'Excelente', max_length=100)),
            ],
        ),
    ]
