# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-27 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0004_auto_20180327_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='nascimento',
            field=models.CharField(default=b'', max_length=8, verbose_name=b'Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
