# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-27 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0005_auto_20180327_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='numero_matricula',
            field=models.CharField(default=b'', max_length=20, unique=True),
        ),
    ]
