# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-03 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0006_aluno_numero_matricula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='nascimento',
            field=models.DateTimeField(),
        ),
    ]
