# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-03 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0007_auto_20180403_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='nascimento',
            field=models.DateField(),
        ),
    ]
