# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-11 15:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0010_auto_20180410_1624'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aluno',
            old_name='sexo',
            new_name='genero',
        ),
    ]
