# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-04 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0012_auto_20180412_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='nascimento',
            field=models.DateTimeField(),
        ),
    ]
