# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-07 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0015_auto_20180607_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='email',
            field=models.EmailField(blank=True, default=b'', max_length=100),
        ),
    ]
