# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-11 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0016_auto_20180607_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='numero_matricula',
            field=models.CharField(default=b'', max_length=20),
        ),
    ]
