# -*- coding: utf-8 -*-

"""
Django settings for sistema project.

Generated by 'django-admin startproject' using Django 1.8.7.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '9p%be%n!3nyd!8vc+_%q&5ltq+s9n&r-bcj&px6%1fmbn@b(%7'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'base',
    'aluno',
    'usuarios',
    'cursos',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'sistema.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'sistema.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'bd',
		'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
		},
        'USER': 'root',
        'PASSWORD': 'PfNca5nw!',
        'HOST': '',
        'PORT': '',
    }
}

# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'
LOGIN_URL = '/login'
#DATE_FORMAT = 'd/m/Y'

########################## Configurações de E-mail ############################

#Enviar Email via terminal
#EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

#Enviar Email via smtp
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
DEFAULT_FROM_EMAIL = 'Contato@ncd.ufes.br <contato@ncd.ufes.br>'
EMAIL_USE_TLS = True
#Configurações abaixo no APP SendGrid
EMAIL_HOST = 'smtp.sendgrid.net'
EMAIL_HOST_USER = 'apikey'
EMAIL_HOST_PASSWORD = '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'
EMAIL_PORT = 587 #TLS

################################################################################


##################### Configurações de Usuários #####################

LOGIN_URL = 'usuarios:login' # Página a ser carregada no Login
LOGIN_REDIRECT_URL = 'base:home' # Página a ser redirecionado após Login
LOGOUT_URL = 'usuarios:logout' # Página de Logout
AUTH_USER_MODEL = 'usuarios.User' # Model de Usuário

######################################################################
